### ISSUE TITLE
HMAC key support using ibm-object-storage-plugin-2.2.12

### ISSUE THREAD

**Issue by hfwen0502** [IBM/ibmcloud-object-storage-plugin#131]
I installed the version 2.2.12 cos plug-in in OCP 4.12 today and it looks like this version does not support HMAC keys for the IBM COS instances anymore. Can someone confirm that this version and beyond only support the API keys moving forward? Thanks!

**Comment by Bhagyashreek8** [comment]
Hi @hfwen0502 IBM COS s3fs plugin version 2.2.12 and all the previous versions do support HMAC credentials. We dont have any changes from our side which would stagger HMAC keys support.

**Comment by hfwen0502** [comment]
BTW, our OCP info and how I install the plug-in:
```
$ oc version
Client Version: 4.10.0
Server Version: 4.11.1
Kubernetes Version: v1.24.0+4f0dd4d
```

The host OS for our workers is RHCOS.
```
helm ibmc install ibm-object-storage-plugin ibm-helm/ibm-object-storage-plugin --set license=true -set bucketAccessPolicy=false --set provider=RHOCP --set platform=openshift --set workerOS=redhat --set kubeDriver=/etc/kubernetes
```

**Comment by Bhagyashreek8** [comment]
HI @hfwen0502 From the error I see, the region i.e. cos.storageClass parameter is not set either by storageclass or in the PVC.

Could you please describe the storageclasses as below
`oc describe sc ibmc-s3fs-cos`
`oc describe sc ibmc-s3fs-cos-perf`

**Comment by Bhagyashreek8** [comment]
Closing the issue since the same secret works in different cluster.
Reopen if required.
