### ISSUE TITLE
ibmcloud-object-storage-plugin fails to start and create StorageClass

### ISSUE THREAD

**Issue by etcshad0vv** [IBM/ibmcloud-object-storage-plugin#41]
Hello team,
I follow the steps from https://cloud.ibm.com/docs/containers?topic=containers-object_storage#install_cos

to install storage provisioner for Cloud Object Storage, however the pod for ibmcloud-object-storage-plugin fails with below error,

`{“level”:“info”,“ts”:“2020-03-06T11:39:43.602Z”,“caller”:“provisioner/main.go:83",“msg”:“Failed to set flag:“,”error”:“no such flag -logtostderr”}
{“level”:“info”,“ts”:“2020-03-06T11:39:43.602Z”,“caller”:“provisioner/main.go:100”,“msg”:“Provisioner specified: “,”provisioner”:“ibm.io/ibmc-s3fs”}
{“level”:“info”,“ts”:“2020-03-06T11:39:43.642Z”,“caller”:“config/config.go:103”,“msg”:“Entry SetUpEvn”}
{“level”:“info”,“ts”:“2020-03-06T11:39:43.708Z”,“caller”:“config/config.go:147”,“msg”:“Exporting cluster-config”,“cluster-info”:{“cluster_id”:“bpcl17td0sa928juvs6g”,“cluster_name”:“prod-hou02-bpcl17td0sa928juvs6g”,“datacenter”:“hou02"}}
{“level”:“info”,“ts”:“2020-03-06T11:39:43.708Z”,“caller”:“config/config.go:111",“msg”:“Exit SetUpEvn”}`

Container Image version: `icr.io/ibm/ibmcloud-object-storage-plugin:1.8.12`

Could you please check?
Thank you

**Comment by anksos** [comment]
@ambiknai any update on that? I am hitting the same error!!! I want to test it and because of this I don't have the possibility, how this cannot be yet fixed yet?

**Comment by ambiknai** [comment]
@etcshad0vv  Your cluster in `hou02` is free one and not supported. Hence the storage classses are not getting created. Could you try on a paid cluster?

**Comment by anksos** [comment]
@ambiknai this is just an excuse or is a requirement? No i cannot try a paid cluster!

**Comment by nkkashyap** [comment]
Hi @anksos Please refer to https://cloud.ibm.com/docs/containers?topic=containers-cs_ov#cluster_types only non-persistent storage is supported for Free Cluster. Please feel free to raise a customer support ticket for IBM Cloud Kubernetes Service.
