### ISSUE TITLE
 ibmcloud-object-storage-plugin-xxxxx goes in crashloopback

### ISSUE THREAD

**Issue by niteenkole** [IBM/ibmcloud-object-storage-plugin#60]
kubectl logs ibmcloud-object-storage-plugin-58766fd575-gghqg -n kube-system -c ibmcloud-object-storage-plugin-container
{"level":"info","ts":"2020-10-31T01:59:41.163Z","caller":"provisioner/main.go:85","msg":"Failed to set flag:","error":"no such flag -logtostderr"}
{"level":"info","ts":"2020-10-31T01:59:41.163Z","caller":"provisioner/main.go:114","msg":"Provisioner specified: ","provisioner":"ibm.io/ibmc-s3fs"}
W1031 01:59:41.163936       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"level":"info","ts":"2020-10-31T01:59:41.165Z","caller":"config/config.go:103","msg":"Entry SetUpEvn"}
{"level":"info","ts":"2020-10-31T01:59:41.213Z","caller":"config/config.go:147","msg":"Exporting cluster-config","cluster-info":{"cluster_id":"bttmdm5w06e4orq29bv0","cluster_name":"prod-wdc04-bttmdm5w06e4orq29bv0","datacenter":"wdc04"}}
{"level":"info","ts":"2020-10-31T01:59:41.213Z","caller":"config/config.go:111","msg":"Exit SetUpEvn"}
I1031 01:59:41.215500       1 controller.go:635] Starting provisioner controller ibm.io/ibmc-s3fs_ibmcloud-object-storage-plugin-58766fd575-gghqg_bd3237e8-1b1c-11eb-97c1-7e825166a711!
I1031 01:59:41.315715       1 controller.go:684] Started provisioner controller ibm.io/ibmc-s3fs_ibmcloud-object-storage-plugin-58766fd575-gghqg_bd3237e8-1b1c-11eb-97c1-7e825166a711!
I1031 01:59:41.315791       1 controller.go:1011] provision "neuvector/neuvector-data" class "ibmc-s3fs-standard-regional": started
I1031 01:59:41.325081       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"neuvector", Name:"neuvector-data", UID:"fba2b9b6-386a-484d-9d39-8907b2354f6d", APIVersion:"v1", ResourceVersion:"6201767", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "neuvector/neuvector-data"
{"level":"info","ts":"2020-10-31T01:59:41.325Z","caller":"provisioner/ibm-s3fs-provisioner.go:229","msg":"neuvector-data:bttmdm5w06e4orq29bv0:Provisioning storage with these spec","requestID":"c29030dd-106c-4f5f-b8c3-8954c9e22655"}
{"level":"info","ts":"2020-10-31T01:59:41.325Z","caller":"provisioner/ibm-s3fs-provisioner.go:230","msg":"neuvector-data:bttmdm5w06e4orq29bv0:PVC Details: ","requestID":"c29030dd-106c-4f5f-b8c3-8954c9e22655","pvc":"pvc-fba2b9b6-386a-484d-9d39-8907b2354f6d"}
{"level":"info","ts":"2020-10-31T01:59:41.351Z","caller":"provisioner/ibm-s3fs-provisioner.go:444","msg":"neuvector-data:bttmdm5w06e4orq29bv0 ConfigBucketAccessPolicy: true, SetAccessPolicy: ","requestID":"c29030dd-106c-4f5f-b8c3-8954c9e22655"}
{"level":"info","ts":"2020-10-31T01:59:41.362Z","caller":"provisioner/ibm-s3fs-provisioner.go:473","msg":"neuvector-data:bttmdm5w06e4orq29bv0 : ClusterType  : vpc-gen2_cruiser","requestID":"c29030dd-106c-4f5f-b8c3-8954c9e22655"}
{"level":"info","ts":"2020-10-31T01:59:44.191Z","caller":"provisioner/ibm-s3fs-provisioner.go:481","msg":"neuvector-data:bttmdm5w06e4orq29bv0 :fetched VPC service endpoints : 10.249.91.180,10.249.94.247,10.249.96.231","requestID":"c29030dd-106c-4f5f-b8c3-8954c9e22655"}
E1031 01:59:44.192288       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/runtime/runtime.go:76
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/runtime/runtime.go:65
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:969
/usr/local/go/src/runtime/panic.go:212
/usr/local/go/src/runtime/signal_unix.go:720
/go/pkg/mod/github.com/!i!b!m/ibm-cos-sdk-go-config@v1.0.0/resourceconfigurationv1/resource_configuration_v1.go:176
/go/src/github.com/IBM/ibmcloud-object-storage-plugin/utils/backend/access_policy.go:41
/go/src/github.com/IBM/ibmcloud-object-storage-plugin/utils/backend/access_policy.go:74
/go/src/github.com/IBM/ibmcloud-object-storage-plugin/provisioner/ibm-s3fs-provisioner.go:552
/go/pkg/mod/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner@v2.2.0+incompatible/controller/controller.go:1099
/go/pkg/mod/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner@v2.2.0+incompatible/controller/controller.go:856
/go/pkg/mod/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner@v2.2.0+incompatible/controller/controller.go:829
/go/pkg/mod/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner@v2.2.0+incompatible/controller/controller.go:747
/go/pkg/mod/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner@v2.2.0+incompatible/controller/controller.go:764
/go/pkg/mod/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner@v2.2.0+incompatible/controller/controller.go:721
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:133
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:134
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:1374
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9c00fa]

goroutine 86 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/runtime/runtime.go:58 +0x10c
panic(0x1622c00, 0x23475d0)
        /usr/local/go/src/runtime/panic.go:969 +0x175
github.com/IBM/ibm-cos-sdk-go-config/resourceconfigurationv1.(*ResourceConfigurationV1).UpdateBucketConfig(0x0, 0xc000a04600, 0x165faa0, 0x1, 0xc0009c9d40)
        /go/pkg/mod/github.com/!i!b!m/ibm-cos-sdk-go-config@v1.0.0/resourceconfigurationv1/resource_configuration_v1.go:176 +0x19a
github.com/IBM/ibmcloud-object-storage-plugin/utils/backend.(*UpdateAPObj).UpdateBucketConfig(0xc0009cea00, 0x0, 0xc000a04600, 0xc0009cea10, 0x0, 0x2)
        /go/src/github.com/IBM/ibmcloud-object-storage-plugin/utils/backend/access_policy.go:41 +0x35
github.com/IBM/ibmcloud-object-storage-plugin/utils/backend.(*UpdateAPObj).UpdateAccessPolicy(0xc0009ce9f0, 0xc0008b60f0, 0x29, 0x0, 0x0, 0xc0008b5640, 0x20, 0x1a0a8e0, 0xc0009cea00, 0xc0008b60f0, ...)
        /go/src/github.com/IBM/ibmcloud-object-storage-plugin/utils/backend/access_policy.go:74 +0x286
github.com/IBM/ibmcloud-object-storage-plugin/provisioner.(*IBMS3fsProvisioner).Provision(0xc0002279d0, 0xc00089dcf0, 0x6, 0xc0008b61e0, 0x28, 0x0, 0x0, 0x0, 0xc0001896c0, 0xc0008b0150, ...)
        /go/src/github.com/IBM/ibmcloud-object-storage-plugin/provisioner/ibm-s3fs-provisioner.go:552 +0x3e13
github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).provisionClaimOperation(0xc000188fc0, 0xc0001896c0, 0x2369fc0, 0x1)
        /go/pkg/mod/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner@v2.2.0+incompatible/controller/controller.go:1099 +0xe75
github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).syncClaim(0xc000188fc0, 0x17dc780, 0xc0001896c0, 0x17dc780, 0xc0001896c0)
        /go/pkg/mod/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner@v2.2.0+incompatible/controller/controller.go:856 +0xad
github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).syncClaimHandler(0xc000188fc0, 0xc000539d00, 0x18, 0x4151e7, 0xc000816248)
        /go/pkg/mod/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner@v2.2.0+incompatible/controller/controller.go:829 +0x8b
github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller.(*ProvisionController).processNextClaimWorkItem.func1(0xc000188fc0, 0x15a5180, 0xc0002db460, 0x0, 0x0)
        /go/pkg/mod/github

**Comment by nkkashyap** [comment]
Appears `getCredentials` returning nil as resource configuration API Key, in case key is missing in the secret. 
@Bhagyashreek8 Can you have a look?

**Comment by Bhagyashreek8** [comment]
@nkkashyap yes, when the `res-conf-apikey` is not set in the secret, the value is passed empty to the resource_configuration_api which inturn returning nil pointer error.

@support 
1. If the customer is not setting up access policies for bucket, then please uninstall and re-install cos plugin helm chart with --set bucketAccessPolicy=false

Command for installing the helm chart:
`helm ibmc install ibm-object-storage-plugin ibm-helm/ibm-object-storage-plugin --set license=true --set bucketAccessPolicy=false`

2. In case customer requires access policies for bucket, please ask the customer to delete the ibmcloud-object-storage-plugin-xxx pod which is in CrashLoopBackOff state and see if it comes up in Running.

3.Then please ask the customer to create the secret with `res-conf-apikey` set in the secret(secret used for PVC creation).
Reference - https://cloud.ibm.com/docs/containers?topic=containers-object_storage#service_credentials
Please create the HMAC credentials with `Manager` role and add the apikey from HMAC credentials as `res-conf-apikey` in the secret which is used for PVC creation.

**Comment by niteenkole** [comment]
deleting ibmcloud-object-storage-plugin-xxx pod which is in CrashLoopBackOff state  comes back with same CrashLoopBackOff state

**Comment by niteenkole** [comment]
uninstalled and installed back with --set bucketAccessPolicy=false and looks good.

**Comment by sandaymin123** [comment]
@nkkashyap @Bhagyashreek8 ^^

**Comment by nkkashyap** [comment]
Hi @niteenkole Could you please confirm the suggested work-around worked and no more issue with the plugin?

**Comment by niteenkole** [comment]
I am good when bucketAccessPolicy=false

question: For any reason if we need to setup access policy this will not work ?

Niteen

**Comment by Bhagyashreek8** [comment]
@niteenkole The NilPointer error has been fixed and will be available in our next release. 
To set the access policy for a bucket, the res-conf-apikey is required to be set in the secret, secret which is used to create PVC.
In your case, the res-conf-apikey was not set in the secret but access policy was enabled, because of which the api was throwing NilPointer error.
In our next image release, you will be able to see a proper error message in the logs when the above case is encountered.

Reference doc to enable access policy - https://cloud.ibm.com/docs/containers?topic=containers-object_storage#cos_auth_ip

Thank you for raising the issue and bringing this to our notice.

**Comment by Bhagyashreek8** [comment]
Fix available in chart release 
https://github.com/IBM/charts/blob/master/repo/ibm-helm/ibm-object-storage-plugin-2.0.5.tgz
