### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by pavuluri** [IBM/ibmcloud-object-storage-plugin#67]
Hi, I am trying to build this plugin on RHEL 7.9.  I followed the instructions, but I get stuck at "make provisioner" step with the following error.

+ cd /go/src/github.com/IBM/ibmcloud-object-storage-plugin/
+ CGO_ENABLED=0 go install -mod=mod -v github.com/IBM/ibmcloud-object-storage-plugin/cmd/provisioner
-mod=mod not supported (can be '', 'readonly', or 'vendor')

Can you please take a look?   Many thanks.

**Comment by ambiknai** [comment]
Hi @pavuluri 
Looks like issue is with Golang base image.
I changed the golang image in `images/driver/Dockerfile.builder` and `images/provisioner/Dockerfile.builder` to `FROM golang:1.15.2` and tried to build. It went fine. Could you do the same and see if it works. 
Meanwhile we will do an end-end test with above change and raise a PR.

**Comment by pavuluri** [comment]
Hi @ambiknai, build works fine now.  Many thanks!
