### ISSUE TITLE
cli plugin commands are too sensitive to whitespace

### ISSUE THREAD

**Issue by lmsurpre** [IBM/ibmcloud-object-storage-plugin#69]
I ran the following command and it failed:
`ibmcloud cos multipart-upload-abort --bucket fhir-export-2fbaaea5-68b5-4775-8a40-c1eb3c4f12d5 --upload-id 01000178-1891-7ea3-d5a5-d4a9a14fb1ea  --key OjSFHLxUpqAYpfWMuMqwpSMMks_hXGAsCMooADOuyXk/Observation_4.ndjson
`

I was very confused for a while.  Then I decided to delete the extra space before --key and it worked.  I don't know what kind of special whitespace char snuck in there (probably a "non-breaking space" char?), but I think the CLI should be more resilient to it.
I didn't try it with other cli commands, but I suspect they will have similar issues.

**Comment by nkkashyap** [comment]
Hi @Imsurpe 
The `ibmcloud cos` issues are tracked by https://github.com/IBM/ibmcloud-cos-cli
Please create a issue under https://github.com/IBM/ibmcloud-cos-cli/issues

**Comment by lmsurpre** [comment]
thanks @nkkashyap, apologies for leaving it in the wrong place
